# Generated by Django 3.0 on 2019-12-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='idUser',
            new_name='user_id',
        ),
    ]
