# Generated by Django 3.0 on 2019-12-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20191214_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
